name: Daily GitHub Streak Commit

on:
  schedule:
    - cron: '0 5 * * *'  # Every day at 10:30 AM IST
  workflow_dispatch:

jobs:
  keep-streak-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Configure Git
        run: |
          git config user.name "Arjun Dixit"
          git config user.email "dixitarjun249@gmail.com"

      - name: Update last_commit.txt with today's date
        run: |
          echo "Last commit date: $(date)" > last_commit.txt

      - name: Commit and push changes
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add last_commit.txt
          git commit -m "📅 Update last_commit.txt - $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git push origin HEAD:main
