name: Daily GitHub Streak Commit

on:
  schedule:
    - cron: '0 5 * * *'  # Runs every day at 5:00 AM UTC (10:30 AM IST)
  workflow_dispatch:     # Allows manual trigger

jobs:
  keep-streak-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make empty commit
        run: |
          git config user.name "Arjundixit18"
          git config user.email "dixitarjun249@gmail.com"
          git commit --allow-empty -m "🕒 Daily GitHub streak keeper"
          git push
